# -*- coding: utf-8 -*-
"""
Single source of truth for the 4:5 "ЛУЧШИЙ ОБРАЗ" layout.

Design canvas is 2048x2560 (4:5). Everything (nano-banana frames, crop rects,
final-output slots) lives in ONE coordinate system, so a region generated by
nano-banana is cropped and pasted back at the exact same pixels.

Outputs (into ./out):
  - template_annotated.png    human reference: every slot, labels, W x H, cell grid
  - template_nano_clean.png   only nano photo frames (black on white) -> feed to model
  - nano_hair3.png            standalone 3-cell frame (front/side/back)
  - nano_eyes5.png            standalone 5-cell frame (5 makeup looks in a row)
  - crops.json                exact pixel rects (at export scale) for cropping + pasting
"""
import json, os
from PIL import Image, ImageDraw, ImageFont

DW, DH = 2048, 2560     # working canvas (4:5)
EXPORT_SCALE = 2        # crops.json / final render at 4096x5120
OUT = os.path.join(os.path.dirname(__file__), "out")
os.makedirs(OUT, exist_ok=True)

# ---- fonts (Windows Arial has Cyrillic) --------------------------------------
def font(sz):
    for p in (r"C:\Windows\Fonts\arialbd.ttf", r"C:\Windows\Fonts\arial.ttf"):
        try:
            return ImageFont.truetype(p, sz)
        except OSError:
            pass
    return ImageFont.load_default()

F_LABEL = font(24)
F_DIM   = font(19)
F_SUB   = font(18)

# ---- geometry ----------------------------------------------------------------
M = 56
COLW = (DW - 2 * M - 40) // 2      # two columns, 40px gutter -> 948
XL = M                              # left column x   = 56
XR = M + COLW + 40                  # right column x  = 1044

# ---- slot table --------------------------------------------------------------
# type:   photo (nano-banana) | draw (our code)
# source: nano | input (user upload) | derive (crop of another slot)
# cells:  N  -> region is split into N horizontal cells (croppable sub-frames)
# Section-header band height reserved above header-bearing slots.
HDR = 44

SLOTS = [
    # key                 x       y     w      h    type    source   cells  label
    ("title",             M,      44,   DW-2*M, 118, "draw",  None,    1, "ЛУЧШИЙ ОБРАЗ (заголовок)"),

    # -- LEFT column --
    ("portrait",          XL,     210,  COLW,  1024, "photo", "nano",  1, "Портрет «после» (hero)"),
    ("before",            XL,     1262, 462,   430,  "photo", "input", 1, "ДО (фото юзера)"),
    ("after_small",       XL+486, 1262, 462,   430,  "photo", "derive",1, "ПОСЛЕ (кроп hero)"),
    ("colortype_palette", XL,     1748, COLW,  392,  "draw",  None,    1, "ЦВЕТОТИП + палитра (свотчи)"),

    # -- RIGHT column --  (headers drawn by the renderer in the HDR band above)
    ("hair_3views",       XR,     210+HDR,  COLW,  300,  "photo", "nano",  3, "Стрижка: спереди/сбоку/сзади"),
    ("hair_swatches",     XR,     600,  COLW,  110,  "draw",  None,    1, "Сравнение цвета волос (до->после)"),
    ("brows",             XR,     754+0,520,   330,  "photo", "nano",  1, "Брови: форма и разметка"),
    ("brows_tips",        XR+544, 754,  404,   330,  "draw",  None,    1, "Брови: рекомендации (текст)"),
    ("eyes_5",            XR,     1128+HDR, COLW, 214, "photo", "nano",  5, "Глаза: 5 макияжей (+ ресницы)"),
    ("contouring",        XR,     1406+HDR, 430,  430,  "photo", "nano",  1, "Скулы/лицо: контуринг"),
    ("contour_swatches",  XR+454, 1406+HDR, 494,  180,  "draw",  None,    1, "Свотчи: скульптор/тени/хайлайт/румяна"),
    ("lips_6",            XR,     1930, COLW,  210,  "draw",  None,    6, "Губы: 6 оттенков (свотчи)"),

    # -- FOOTER (full width) --
    ("footer",            M,      2216, DW-2*M, 296, "draw", None,     4, "РЕЗУЛЬТАТ: 4 колонки текста"),
]

def cell_rects(x, y, w, h, n, gap=8):
    """Split a region into n horizontal cells; return list of (x,y,w,h)."""
    if n <= 1:
        return [(x, y, w, h)]
    cw = (w - gap * (n - 1)) / n
    return [(int(round(x + i * (cw + gap))), y, int(round(cw)), h) for i in range(n)]

# ---- crops.json (export scale) ----------------------------------------------
def build_crops():
    S = EXPORT_SCALE
    data = {"canvas": [DW * S, DH * S], "design": [DW, DH], "scale": S, "slots": {}}
    for key, x, y, w, h, typ, src, cells, label in SLOTS:
        entry = {"rect": [x*S, y*S, w*S, h*S], "type": typ, "source": src, "label": label}
        if cells > 1 and typ == "photo":
            entry["cells"] = [[cx*S, cy*S, cw*S, ch*S] for (cx, cy, cw, ch) in cell_rects(x, y, w, h, cells)]
        data["slots"][key] = entry
    with open(os.path.join(OUT, "crops.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return data

# ---- annotated reference -----------------------------------------------------
COL_PHOTO = (208, 226, 245)
COL_DRAW  = (235, 235, 235)
COL_LINE  = (30, 30, 30)
COL_CELL  = (120, 120, 120)

def draw_annotated():
    img = Image.new("RGB", (DW, DH), "white")
    d = ImageDraw.Draw(img)
    for key, x, y, w, h, typ, src, cells, label in SLOTS:
        fill = COL_PHOTO if typ == "photo" else COL_DRAW
        d.rectangle([x, y, x+w, y+h], fill=fill, outline=COL_LINE, width=3)
        if cells > 1:
            for (cx, cy, cw, ch) in cell_rects(x, y, w, h, cells):
                d.rectangle([cx, cy, cx+cw, cy+ch], outline=COL_CELL, width=2)
        d.text((x+12, y+10), label, fill=(0, 0, 0), font=F_LABEL)
        tag = f"{w}x{h}px" + (f"  x{cells}" if cells > 1 else "")
        d.text((x+12, y+40), tag, fill=(90, 90, 90), font=F_DIM)
        d.text((x+12, y+h-28), f"[{typ}/{src or '-'}]", fill=(120, 120, 120), font=F_SUB)
    img.save(os.path.join(OUT, "template_annotated.png"))

# ---- clean nano frames -------------------------------------------------------
def draw_nano_clean():
    img = Image.new("RGB", (DW, DH), "white")
    d = ImageDraw.Draw(img)
    for key, x, y, w, h, typ, src, cells, label in SLOTS:
        if typ != "photo" or src != "nano":
            continue
        d.rectangle([x, y, x+w, y+h], outline="black", width=6)
        if cells > 1:
            for (cx, cy, cw, ch) in cell_rects(x, y, w, h, cells):
                d.rectangle([cx, cy, cx+cw, cy+ch], outline="black", width=4)
    img.save(os.path.join(OUT, "template_nano_clean.png"))

def draw_strip(w, h, n, name):
    img = Image.new("RGB", (w, h), "white")
    d = ImageDraw.Draw(img)
    d.rectangle([2, 2, w-3, h-3], outline="black", width=6)
    for (cx, cy, cw, ch) in cell_rects(0, 0, w, h, n):
        d.rectangle([cx+2, cy+2, cx+cw-2, cy+ch-2], outline="black", width=4)
    img.save(os.path.join(OUT, name))

if __name__ == "__main__":
    data = build_crops()
    draw_annotated()
    draw_nano_clean()
    draw_strip(948, 300, 3, "nano_hair3.png")
    draw_strip(948, 214, 5, "nano_eyes5.png")
    photo = [s for s in SLOTS if s[6] == "nano"]
    print(f"OK ({DW}x{DH}, 4:5) -> {OUT}")
    print(f"nano-banana generations needed: {len(photo)}")
    for s in photo:
        print(f"  - {s[0]:14s} {s[3]}x{s[4]}px" + (f"  cells={s[7]}" if s[7] > 1 else ""))
